### ISSUE TITLE
HTML Validatorda chiqgan xatolarni to'g'irlash kerak.

### ISSUE THREAD

**Issue by darxanov** [akramjonnuriddinov/Ansormed-001#1]
https://prnt.sc/OMOjeaAJ8E6N

Manashu rasmdagi 4 ta xatoni to'girlash kerak ekan.

**Comment by akramjonnuriddinov** [comment]
Bu xatoliklar svg formatdagi logolarni xatosi. Biz bu xatolarni to'g'rilay olmasak kerak.

**Comment by frontendtester** [comment]
Rasmni boshqa formatda chiqarish kerak bo'ladi. SVG maketdagi logoga mos emas.
