### ISSUE TITLE
Footerdagi logoni active si xato ekan

### ISSUE THREAD

**Issue by shohruh-yoqubov** [akramjonnuriddinov/Ansormed-001#4]
https://github.com/akramjonnuriddinov/Ansormed-001  Footerdagi logoni active si #fff opasity si esa 0.6 boladi

**Comment by akramjonnuriddinov** [comment]
To'g'riladim. Raxmat.

**Comment by frontendtester** [comment]
@shohruh-yoqubov , reponing linkini berish shart emas.
